---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должени показывать количество добавленных товаров в корзину
  - Пользователь должен быть подключен к сети
