---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должени показывать количество добавленных товаров в корзину
  - Пользователь должен быть подключен к сети
